@startuml supported_countries
    entity supported_countries as "SupportedCountry"  {
        * id: UUID <<pk>>
        * name: VARCHAR NOT NULL
        * iso_code: VARCHAR NOT NULL
        * is_enabled: Boolean DEFAULT true
        * created_on: Timestamp DEFAULT now()
        * updated_on: Timestamp DEFAULT now()
    }

    entity supported_languages as "SupportedLanguage"  {
        * id: UUID <<pk>>
        * label: VARCHAR NOT NULL
        * iso_code: VARCHAR NOT NULL
        * created_on: Timestamp DEFAULT now()
        * updated_on: Timestamp DEFAULT now()
    }

    entity supported_currencies as "SupportedCurrency" {
        * id: UUID <<pk>>
        * label: VARCHAR NOT NULL
        * iso_code: VARCHAR NOT NULL
        * created_on: Timestamp DEFAULT now()
        * updated_on: Timestamp DEFAULT now()
    }

    entity supported_country_language as "SupportedCountryLanguage"  {
        * id: UUID <<pk>>
        * country_id: UUID <<fk>> NOT NULL
        * language_id: UUID <<fk>> NOT NULL
        * created_on: Timestamp DEFAULT now()
        * updated_on: Timestamp DEFAULT now()
    }

    entity supported_country_currencies as "SupportedCountryCurrency"  {
        * id: UUID <<pk>>
        * country_id: UUID <<fk>> NOT NULL
        * currency_id: UUID <<fk>> NOT NULL
        * created_on: Timestamp DEFAULT now()
        * updated_on: Timestamp DEFAULT now()
    }

    supported_country_language }|-- supported_countries
    supported_country_currencies }|-- supported_countries
    supported_languages }|-- supported_country_language
    supported_country_currencies }|-- supported_currencies

@enduml